### PR TITLE
add meetup link w/ icon

### PR DESCRIPTION
**Pull request by jaredrhodes**
screen shot 2016-04-01 at 5 42 07 pm

### CODE REVIEW

**Comment by shrinkray** [comment]
I'd like to do the meetup link differently. My idea is to add a centered image link below the social media items without the button chrome. The purpose of this site is to promote sponsorship. For that matter, the current social media buttons need muting too.

**Comment by jaredrhodes** [comment]
If primary goal is sponsorship then I might consider putting a sponsorship message and CTA "above the fold". Social links are secondary. Also, I'm going to create topical branches for updates so we don't get crazy merge scenarios from branches with multiple fixes.

**Comment by jaredrhodes** [comment]
I'm closing this since it's not the right solution. I'll revert the develop branch as this should have been in a different branch, anyhow.

**Comment by jaredrhodes** [comment]
Easier to delete branch. I'll create a new one off master.

**Pull request closed without merging**
